### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/wal#1]
- [x] Finish flags.
    - [x] Use `getopts`.
    - [x] `-i` take a dir as a path too.
    - [x] `-h` help
    - [x] `-q` quiet
    - [ ] ???
- [x] Detect ~~`dunst`~~, `i3` and other programs automatically.
    - [x] `i3`
    - [x] ~~`dunst`~~
    - Programs must be updated/reloaded in a way that works 100% of the time and doesn't mess with the user's configuration.
    - [ ] ???
- [x] Optimization.
- [ ] Add support for outputting to other formats.
    - [x] `scss`
    - [x] `envars`
    - [ ] ???
- [x] Cleanup.
- [x] Documentation.
- [x] Wallpaper setter.
    - [x] Auto detect wallpaper setters.
- [ ] Possibly remove `reload_env()` and encourage users to write their own scripts.
